[Variables]
    Player=Spotify
    FontName=Product Sans
    FontColor=250,250,250             
    FontColor2=250,250,250            
    FontSize=14                       
    FontSize2=9                       
    FontSize3=11                      
    SolidColor=250,250,250            
    SolidColor2=220,220,220     
    SolidColor3=230,230,230       
    SolidColor4=250,250,250           
    SolidColor5=250,250,250           
    SolidColor6=240,240,240     
    BarColor=100,100,100
    color.BG=ffffff
    color.Font=ffffff

    WeatherLocation=Colombo
    ; Just enter your city's name or your address here or whatever. Anything should work here.
    ; TIP: Check Rainmeter's log to see what location it got.

    WeatherUnits=Metric
    ; The units of the weather info. Valid values are "Metric" and "Imperial".

    Language=en
    ; The language code for the weather information. Most languages are supported, but it's not guaranteed to work.
    ; Recommended and working values are (kind of grouped by area):
    ; "en" (English),
    ; "de" (German), "nl" (Dutch), "fr" (French), "es" (Spanish), "pt" (Portuguese), "it" (Italian),
    ; "sv" (Swedish), "no" (Norwegian), "fi" (Finnish), "da" (Danish),
    ; "ar" (Arabic), "tr" (Turkish),"hr" (Croatian), "el" (Greek), "cs" (Czech),
    ; "ru" (Russian), "pl" (Polish), "ro" (Romanian), "sk" (Slovak), "uk" (Ukrainian),"et" (Estonian), "hu" (Hungarian),
    ; "zh" (Chinese),"ja" (Japanese), "ko" (Korean), "th" (Thai), "vi" (Vietnamese), "hi" (Hindi), "bn" (Bangla).